// Generated by gencpp from file myspeechrecognition/speechcommand.msg
// DO NOT EDIT!


#ifndef MYSPEECHRECOGNITION_MESSAGE_SPEECHCOMMAND_H
#define MYSPEECHRECOGNITION_MESSAGE_SPEECHCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace myspeechrecognition
{
template <class ContainerAllocator>
struct speechcommand_
{
  typedef speechcommand_<ContainerAllocator> Type;

  speechcommand_()
    : header()
    , mode()
    , argument()  {
    }
  speechcommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , mode(_alloc)
    , argument(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mode_type;
  _mode_type mode;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _argument_type;
  _argument_type argument;





  typedef boost::shared_ptr< ::myspeechrecognition::speechcommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::myspeechrecognition::speechcommand_<ContainerAllocator> const> ConstPtr;

}; // struct speechcommand_

typedef ::myspeechrecognition::speechcommand_<std::allocator<void> > speechcommand;

typedef boost::shared_ptr< ::myspeechrecognition::speechcommand > speechcommandPtr;
typedef boost::shared_ptr< ::myspeechrecognition::speechcommand const> speechcommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::myspeechrecognition::speechcommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::myspeechrecognition::speechcommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace myspeechrecognition

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'myspeechrecognition': ['/home/imstevenpm/EMARO_1ST_SEMESTER/SOFAR/Group Project/myworkspace/src/myspeechrecognition/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::myspeechrecognition::speechcommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::myspeechrecognition::speechcommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myspeechrecognition::speechcommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myspeechrecognition::speechcommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myspeechrecognition::speechcommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myspeechrecognition::speechcommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::myspeechrecognition::speechcommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f47b16802a5c9e8b62fe293298cf8f4";
  }

  static const char* value(const ::myspeechrecognition::speechcommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f47b16802a5c9e8ULL;
  static const uint64_t static_value2 = 0xb62fe293298cf8f4ULL;
};

template<class ContainerAllocator>
struct DataType< ::myspeechrecognition::speechcommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "myspeechrecognition/speechcommand";
  }

  static const char* value(const ::myspeechrecognition::speechcommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::myspeechrecognition::speechcommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string mode\n"
"string argument\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::myspeechrecognition::speechcommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::myspeechrecognition::speechcommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.mode);
      stream.next(m.argument);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct speechcommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::myspeechrecognition::speechcommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::myspeechrecognition::speechcommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mode);
    s << indent << "argument: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.argument);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYSPEECHRECOGNITION_MESSAGE_SPEECHCOMMAND_H
